FROM ruby:3.3
WORKDIR /app

# 基本パッケージ
RUN apt-get update -qq && apt-get install -y curl gnupg postgresql-client

# Node.js v20 + Yarn
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && corepack enable

# Gemfile が無いので、ここはコメントアウト
# COPY Gemfile Gemfile.lock ./
# RUN bundle install

COPY . .
CMD ["bash"]
